#ifndef MOMENTUM_VERSION_H
#define MOMENTUM_VERSION_H

#define MOMENTUM_VERSION_MAJOR 1
#define MOMENTUM_VERSION_MINOR 1
#define MOMENTUM_VERSION_BUG 0
#define MOMENTUM_VERSION_STAGE PF_Stage_DEVELOP
#define MOMENTUM_VERSION_BUILD 28
#define MOMENTUM_VERSION_PIPL 557084 /* PF_VERSION(1, 1, 0, DEVELOP, 28) */

#endif
