#ifndef MOMENTUM_VERSION_H
#define MOMENTUM_VERSION_H

#define MOMENTUM_VERSION_MAJOR 0
#define MOMENTUM_VERSION_MINOR 1
#define MOMENTUM_VERSION_BUG 0
#define MOMENTUM_VERSION_STAGE PF_Stage_DEVELOP
#define MOMENTUM_VERSION_BUILD 1

#endif
