#ifndef MOMENTUM_VERSION_H
#define MOMENTUM_VERSION_H

#define MOMENTUM_VERSION_MAJOR 1
#define MOMENTUM_VERSION_MINOR 1
#define MOMENTUM_VERSION_BUG 1
#define MOMENTUM_VERSION_STAGE PF_Stage_DEVELOP
#define MOMENTUM_VERSION_BUILD 30
#define MOMENTUM_VERSION_PIPL 559134 /* PF_VERSION(1, 1, 1, DEVELOP, 30) */

#endif
