#include "rendering/bitmap/backends/metal/shaders.h"

namespace momentum {
namespace bitmap {
namespace metal {

const char* ShaderSource() {
  static const char source[] =
  "#include <metal_stdlib>\n"
   "using namespace metal;\n"
   "struct ViewportUniforms {\n"
   "  float2 viewportSize;\n"
   "};\n"
   "struct CopyUniforms {\n"
   "  uint width;\n"
   "  uint height;\n"
   "  uint rowPixels;\n"
   "  uint pad;\n"
   "  float sourceOriginX;\n"
   "  float sourceOriginY;\n"
   "  float sourceStepX;\n"
   "  float sourceStepY;\n"
   "  uint logicalWidth;\n"
   "  uint logicalHeight;\n"
   "};\n"
   "struct BlendUniforms {\n"
   "  uint width;\n"
   "  uint height;\n"
   "  int blendMode;\n"
   "  uint erase;\n"
   "  float eraseStrength;\n"
   "};\n"
   "struct FilterUniforms {\n"
   "  uint width;\n"
   "  uint height;\n"
   "  int filterKind;\n"
   "  float value;\n"
   "};\n"
   "struct PathFillContour {\n"
   "  uint vertexStart;\n"
   "  uint vertexCount;\n"
   "};\n"
   "struct PathFillUniforms {\n"
   "  uint regionOriginX;\n"
   "  uint regionOriginY;\n"
   "  uint regionWidth;\n"
   "  uint regionHeight;\n"
   "  uint canvasWidth;\n"
   "  uint canvasHeight;\n"
   "  uint contourStart;\n"
   "  uint contourCount;\n"
   "  uint clipContourStart;\n"
   "  uint clipContourCount;\n"
   "  float2 viewportSize;\n"
   "  float4 color;\n"
   "  float4 bounds;\n"
   "  float4 clipBounds;\n"
   "};\n"
   "struct FillTriangleData {\n"
   "  float2 a;\n"
   "  float2 b;\n"
   "  float2 c;\n"
   "};\n"
   "struct EdgeSegment {\n"
   "  float2 a;\n"
   "  float2 b;\n"
   "};\n"
   "struct EdgeDistanceInfo {\n"
   "  float distance;\n"
   "  float2 a;\n"
   "  float2 b;\n"
   "};\n"
   "struct FillRasterUniforms {\n"
   "  uint regionOriginX;\n"
   "  uint regionOriginY;\n"
   "  uint regionWidth;\n"
   "  uint regionHeight;\n"
   "  uint canvasWidth;\n"
   "  uint canvasHeight;\n"
   "  uint triangleCount;\n"
   "  uint edgeCount;\n"
   "  uint clipContourStart;\n"
   "  uint clipContourCount;\n"
   "  float2 viewportSize;\n"
   "  float4 color;\n"
   "  float4 bounds;\n"
   "  float4 clipBounds;\n"
   "};\n"
   "struct ImageVertex {\n"
   "  float2 position;\n"
   "  float2 uv;\n"
   "  float4 tint;\n"
   "};\n"
   "struct ImageVertexOut {\n"
   "  float4 position [[position]];\n"
   "  float2 worldPoint;\n"
   "  float2 uv;\n"
   "  float4 tint;\n"
   "};\n"
   "float distance_to_segment(float2 point, float2 start, float2 end) {\n"
   "  float2 delta = end - start;\n"
   "  float lengthSquared = max(dot(delta, delta), 1e-6f);\n"
   "  float t = clamp(dot(point - start, delta) / lengthSquared, 0.0f, 1.0f);\n"
   "  float2 projection = start + delta * t;\n"
   "  return length(point - projection);\n"
   "}\n"
   "bool point_in_triangle(float2 point, float2 a, float2 b, float2 c) {\n"
   "  float2 v0 = b - a;\n"
   "  float2 v1 = c - b;\n"
   "  float2 v2 = a - c;\n"
   "  float c0 = v0.x * (point.y - a.y) - v0.y * (point.x - a.x);\n"
   "  float c1 = v1.x * (point.y - b.y) - v1.y * (point.x - b.x);\n"
   "  float c2 = v2.x * (point.y - c.y) - v2.y * (point.x - c.x);\n"
   "  bool hasNeg = (c0 < 0.0f) || (c1 < 0.0f) || (c2 < 0.0f);\n"
   "  bool hasPos = (c0 > 0.0f) || (c1 > 0.0f) || (c2 > 0.0f);\n"
   "  return !(hasNeg && hasPos);\n"
   "}\n"
   "float edge_coverage_from_signed_distance(float signedDistance) {\n"
   "  constexpr float aaHalfWidth = 0.5f;\n"
   "  return clamp((aaHalfWidth - signedDistance) / (aaHalfWidth * 2.0f), 0.0f, 1.0f);\n"
   "}\n"
   "bool point_in_any_fill_triangle(float2 point, device const FillTriangleData* triangles, uint triangleCount) {\n"
   "  for (uint triangleIndex = 0; triangleIndex < triangleCount; ++triangleIndex) {\n"
   "    FillTriangleData triangle = triangles[triangleIndex];\n"
   "    if (point_in_triangle(point, triangle.a, triangle.b, triangle.c)) {\n"
   "      return true;\n"
   "    }\n"
   "  }\n"
   "  return false;\n"
   "}\n"
   "EdgeDistanceInfo nearest_fill_edge_info(float2 point, device const EdgeSegment* edges, uint edgeCount) {\n"
   "  EdgeDistanceInfo info;\n"
   "  info.distance = INFINITY;\n"
   "  info.a = float2(0.0f);\n"
   "  info.b = float2(0.0f);\n"
   "  for (uint edgeIndex = 0; edgeIndex < edgeCount; ++edgeIndex) {\n"
   "    EdgeSegment edge = edges[edgeIndex];\n"
   "    float distanceValue = distance_to_segment(point, edge.a, edge.b);\n"
   "    if (distanceValue < info.distance) {\n"
   "      info.distance = distanceValue;\n"
   "      info.a = edge.a;\n"
   "      info.b = edge.b;\n"
   "    }\n"
   "  }\n"
   "  return info;\n"
   "}\n"
   "int winding_at_point(float2 point, device const float2* vertices, device const PathFillContour* contours, uint contourStart, uint contourCount) {\n"
   "  int winding = 0;\n"
   "  for (uint contourIndex = 0; contourIndex < contourCount; ++contourIndex) {\n"
   "    PathFillContour contour = contours[contourStart + contourIndex];\n"
   "    if (contour.vertexCount < 2u) {\n"
   "      continue;\n"
   "    }\n"
   "    for (uint vertexIndex = 0; vertexIndex < contour.vertexCount; ++vertexIndex) {\n"
   "      float2 a = vertices[contour.vertexStart + vertexIndex];\n"
   "      float2 b = vertices[contour.vertexStart + ((vertexIndex + 1u) % contour.vertexCount)];\n"
   "      bool upward = (a.y <= point.y) && (b.y > point.y);\n"
   "      bool downward = (a.y > point.y) && (b.y <= point.y);\n"
   "      if (!upward && !downward) {\n"
   "        continue;\n"
   "      }\n"
   "      float cross = (b.x - a.x) * (point.y - a.y) - (point.x - a.x) * (b.y - a.y);\n"
   "      if (upward && cross > 0.0f) {\n"
   "        winding += 1;\n"
   "      } else if (downward && cross < 0.0f) {\n"
   "        winding -= 1;\n"
   "      }\n"
   "    }\n"
   "  }\n"
   "  return winding;\n"
   "}\n"
   "EdgeDistanceInfo nearest_path_edge_info(float2 point, device const float2* vertices, device const PathFillContour* contours, uint contourStart, uint contourCount) {\n"
   "  EdgeDistanceInfo info;\n"
   "  info.distance = INFINITY;\n"
   "  info.a = float2(0.0f);\n"
   "  info.b = float2(0.0f);\n"
   "  for (uint contourIndex = 0; contourIndex < contourCount; ++contourIndex) {\n"
   "    PathFillContour contour = contours[contourStart + contourIndex];\n"
   "    if (contour.vertexCount < 2u) {\n"
   "      continue;\n"
   "    }\n"
   "    for (uint vertexIndex = 0; vertexIndex < contour.vertexCount; ++vertexIndex) {\n"
   "      float2 a = vertices[contour.vertexStart + vertexIndex];\n"
   "      float2 b = vertices[contour.vertexStart + ((vertexIndex + 1u) % contour.vertexCount)];\n"
   "      float distanceValue = distance_to_segment(point, a, b);\n"
   "      if (distanceValue < info.distance) {\n"
   "        info.distance = distanceValue;\n"
   "        info.a = a;\n"
   "        info.b = b;\n"
   "      }\n"
   "    }\n"
   "  }\n"
   "  return info;\n"
   "}\n"
   "bool edge_is_axis_aligned(float2 a, float2 b) {\n"
   "  float2 delta = fabs(b - a);\n"
   "  return delta.x <= 1e-3f || delta.y <= 1e-3f;\n"
   "}\n"
   "bool edge_is_pixel_aligned(float2 a, float2 b) {\n"
   "  float2 delta = fabs(b - a);\n"
   "  if (delta.x <= 1e-3f) {\n"
   "    return fabs(a.x - round(a.x)) <= 0.125f;\n"
   "  }\n"
   "  if (delta.y <= 1e-3f) {\n"
   "    return fabs(a.y - round(a.y)) <= 0.125f;\n"
   "  }\n"
   "  return false;\n"
   "}\n"
   "float resolve_edge_coverage(float signedDistance, float2 a, float2 b) {\n"
   "  if (edge_is_axis_aligned(a, b) && edge_is_pixel_aligned(a, b)) {\n"
   "    return signedDistance < 0.0f ? 1.0f : 0.0f;\n"
   "  }\n"
   "  return edge_coverage_from_signed_distance(signedDistance);\n"
   "}\n"
   "float sample_clip_alpha(texture2d<float> clipTexture, float2 worldPoint, float2 viewportSize) {\n"
   "  constexpr sampler clipSampler(coord::normalized, address::clamp_to_edge, filter::linear);\n"
   "  float2 uv = float2(\n"
   "    viewportSize.x > 0.0f ? worldPoint.x / viewportSize.x : 0.0f,\n"
   "    viewportSize.y > 0.0f ? worldPoint.y / viewportSize.y : 0.0f);\n"
   "  return clamp(clipTexture.sample(clipSampler, uv).a, 0.0f, 1.0f);\n"
   "}\n"
   "float analytic_clip_coverage(float2 point, device const float2* vertices, device const PathFillContour* contours, uint contourStart, uint contourCount, float4 clipBounds) {\n"
   "  if (contourCount == 0u) {\n"
   "    return 1.0f;\n"
   "  }\n"
   "  if (point.x < clipBounds.x - 1.0f || point.y < clipBounds.y - 1.0f || point.x > clipBounds.z + 1.0f || point.y > clipBounds.w + 1.0f) {\n"
   "    return 0.0f;\n"
   "  }\n"
   "  bool inside = winding_at_point(point, vertices, contours, contourStart, contourCount) != 0;\n"
   "  EdgeDistanceInfo edgeInfo = nearest_path_edge_info(point, vertices, contours, contourStart, contourCount);\n"
   "  float signedDistance = inside ? -edgeInfo.distance : edgeInfo.distance;\n"
   "  return resolve_edge_coverage(signedDistance, edgeInfo.a, edgeInfo.b);\n"
   "}\n"
   "vertex ImageVertexOut image_vertex(\n"
   "  uint vertexId [[vertex_id]],\n"
   "  constant ImageVertex* vertices [[buffer(0)]],\n"
   "  constant ViewportUniforms& viewport [[buffer(1)]]) {\n"
   "  ImageVertex value = vertices[vertexId];\n"
   "  float clipX = viewport.viewportSize.x > 0.0f ? (value.position.x / viewport.viewportSize.x) * 2.0f - 1.0f : -1.0f;\n"
   "  float clipY = viewport.viewportSize.y > 0.0f ? 1.0f - (value.position.y / viewport.viewportSize.y) * 2.0f : 1.0f;\n"
   "  ImageVertexOut out;\n"
   "  out.position = float4(clipX, clipY, 0.0f, 1.0f);\n"
   "  out.worldPoint = value.position;\n"
   "  out.uv = value.uv;\n"
   "  out.tint = value.tint;\n"
   "  return out;\n"
   "}\n"
   "fragment float4 image_fragment(\n"
  "  ImageVertexOut in [[stage_in]],\n"
  "  constant ViewportUniforms& viewport [[buffer(0)]],\n"
  "  texture2d<float> imageTexture [[texture(0)]],\n"
  "  texture2d<float> clipTexture [[texture(1)]]) {\n"
  "  constexpr sampler imageSampler(coord::normalized, address::clamp_to_edge, filter::linear);\n"
   "  float4 sampledPremul = imageTexture.sample(imageSampler, in.uv);\n"
   "  float sampledAlpha = clamp(sampledPremul.a, 0.0f, 1.0f);\n"
   "  float3 sampledStraight = sampledAlpha > 1e-6f ? sampledPremul.rgb / sampledAlpha : float3(0.0f);\n"
   "  float3 tintedStraight = sampledStraight * in.tint.rgb;\n"
   "  float clipAlpha = sample_clip_alpha(clipTexture, in.worldPoint, viewport.viewportSize);\n"
   "  float alpha = sampledAlpha * in.tint.a * clipAlpha;\n"
   "  return float4(tintedStraight * alpha, alpha);\n"
   "}\n"
   "fragment float4 text_image_fragment(\n"
   "  ImageVertexOut in [[stage_in]],\n"
   "  constant ViewportUniforms& viewport [[buffer(0)]],\n"
   "  texture2d<float> imageTexture [[texture(0)]],\n"
   "  texture2d<float> clipTexture [[texture(1)]]) {\n"
   "  constexpr sampler imageSampler(coord::normalized, address::clamp_to_edge, filter::linear);\n"
   "  float4 sampledPremul = imageTexture.sample(imageSampler, in.uv);\n"
   "  float sampledAlpha = clamp(sampledPremul.a, 0.0f, 1.0f);\n"
   "  float3 sampledStraight = sampledAlpha > 1e-6f ? sampledPremul.rgb / sampledAlpha : float3(0.0f);\n"
   "  float3 tintedStraight = sampledStraight * in.tint.rgb;\n"
   "  float clipAlpha = sample_clip_alpha(clipTexture, in.worldPoint, viewport.viewportSize);\n"
   "  float alpha = sampledAlpha * in.tint.a * clipAlpha;\n"
   "  return float4(tintedStraight * alpha, alpha);\n"
   "}\n"
   "float softlight_d(float backdrop) {\n"
   "  return backdrop <= 0.25f\n"
   "    ? ((16.0f * backdrop - 12.0f) * backdrop + 4.0f) * backdrop\n"
   "    : sqrt(backdrop);\n"
   "}\n"
   "float canvas_blend_channel(float backdrop, float source, int blendMode) {\n"
   "  switch (blendMode) {\n"
   "    case 402: return min(backdrop, source);\n"
   "    case 403: return max(backdrop, source);\n"
   "    case 404: return fabs(backdrop - source);\n"
   "    case 405: return backdrop + source - 2.0f * backdrop * source;\n"
   "    case 406: return backdrop * source;\n"
   "    case 407: return backdrop + source - backdrop * source;\n"
   "    case 410: return backdrop <= 0.5f\n"
   "      ? 2.0f * backdrop * source\n"
   "      : 1.0f - 2.0f * (1.0f - backdrop) * (1.0f - source);\n"
   "    case 411: return source <= 0.5f\n"
   "      ? 2.0f * backdrop * source\n"
   "      : 1.0f - 2.0f * (1.0f - backdrop) * (1.0f - source);\n"
   "    case 412: return source <= 0.5f\n"
   "      ? backdrop - (1.0f - 2.0f * source) * backdrop * (1.0f - backdrop)\n"
   "      : backdrop + (2.0f * source - 1.0f) * (softlight_d(backdrop) - backdrop);\n"
   "    case 413: return source >= 1.0f\n"
   "      ? 1.0f\n"
   "      : min(1.0f, backdrop / max(1.0f - source, 1e-5f));\n"
   "    case 414: return source <= 0.0f\n"
   "      ? 0.0f\n"
   "      : 1.0f - min(1.0f, (1.0f - backdrop) / max(source, 1e-5f));\n"
   "    case 400:\n"
   "    default:\n"
   "      return source;\n"
   "  }\n"
   "}\n"
   "float3 canvas_blend_rgb(float3 backdrop, float3 source, int blendMode) {\n"
   "  return float3(\n"
   "    canvas_blend_channel(backdrop.r, source.r, blendMode),\n"
   "    canvas_blend_channel(backdrop.g, source.g, blendMode),\n"
   "    canvas_blend_channel(backdrop.b, source.b, blendMode)\n"
   "  );\n"
   "}\n"
   "kernel void rasterize_fill_analytic(\n"
   "  device const FillTriangleData* triangles [[buffer(0)]],\n"
   "  device const EdgeSegment* edges [[buffer(1)]],\n"
   "  constant FillRasterUniforms& uniforms [[buffer(2)]],\n"
   "  device const float2* clipVertices [[buffer(3)]],\n"
   "  device const PathFillContour* clipContours [[buffer(4)]],\n"
   "  texture2d<float, access::read_write> destinationTexture [[texture(0)]],\n"
   "  texture2d<float> clipTexture [[texture(1)]],\n"
   "  uint2 gid [[thread_position_in_grid]]) {\n"
   "  if (gid.x >= uniforms.regionWidth || gid.y >= uniforms.regionHeight) {\n"
   "    return;\n"
   "  }\n"
   "  const uint px = uniforms.regionOriginX + gid.x;\n"
   "  const uint py = uniforms.regionOriginY + gid.y;\n"
   "  if (px >= uniforms.canvasWidth || py >= uniforms.canvasHeight) {\n"
   "    return;\n"
   "  }\n"
   "  const float2 point = float2(float(px) + 0.5f, float(py) + 0.5f);\n"
   "  if (point.x < uniforms.bounds.x - 1.0f || point.y < uniforms.bounds.y - 1.0f ||\n"
   "      point.x > uniforms.bounds.z + 1.0f || point.y > uniforms.bounds.w + 1.0f) {\n"
   "    return;\n"
   "  }\n"
   "  const bool inside = point_in_any_fill_triangle(point, triangles, uniforms.triangleCount);\n"
   "  if (!inside && uniforms.edgeCount == 0u) {\n"
   "    return;\n"
   "  }\n"
   "  const EdgeDistanceInfo edgeInfo = uniforms.edgeCount > 0u\n"
   "    ? nearest_fill_edge_info(point, edges, uniforms.edgeCount)\n"
   "    : EdgeDistanceInfo{inside ? 0.0f : INFINITY, float2(0.0f), float2(0.0f)};\n"
   "  const float nearestDistance = edgeInfo.distance;\n"
   "  const float signedDistance = inside ? -nearestDistance : nearestDistance;\n"
   "  const float coverage = resolve_edge_coverage(signedDistance, edgeInfo.a, edgeInfo.b);\n"
   "  if (coverage <= 1e-6f) {\n"
   "    return;\n"
   "  }\n"
   "  float clipAlpha = uniforms.clipContourCount > 0u\n"
   "    ? analytic_clip_coverage(point, clipVertices, clipContours, uniforms.clipContourStart, uniforms.clipContourCount, uniforms.clipBounds)\n"
   "    : sample_clip_alpha(clipTexture, point, uniforms.viewportSize);\n"
   "  float srcA = clamp(uniforms.color.a * coverage * clipAlpha, 0.0f, 1.0f);\n"
   "  if (srcA <= 1e-6f) {\n"
   "    return;\n"
   "  }\n"
   "  float4 src = float4(uniforms.color.rgb * srcA, srcA);\n"
   "  float4 dst = destinationTexture.read(uint2(px, py));\n"
   "  float oneMinusSrcA = 1.0f - srcA;\n"
   "  float4 outColor = float4(src.rgb + dst.rgb * oneMinusSrcA, srcA + dst.a * oneMinusSrcA);\n"
   "  destinationTexture.write(outColor, uint2(px, py));\n"
   "}\n"
   "kernel void rasterize_path_fill_nonzero(\n"
   "  device const float2* vertices [[buffer(0)]],\n"
   "  device const PathFillContour* contours [[buffer(1)]],\n"
   "  constant PathFillUniforms& uniforms [[buffer(2)]],\n"
   "  texture2d<float, access::read_write> destinationTexture [[texture(0)]],\n"
   "  texture2d<float> clipTexture [[texture(1)]],\n"
   "  uint2 gid [[thread_position_in_grid]]) {\n"
   "  if (gid.x >= uniforms.regionWidth || gid.y >= uniforms.regionHeight) {\n"
   "    return;\n"
   "  }\n"
   "  const uint px = uniforms.regionOriginX + gid.x;\n"
   "  const uint py = uniforms.regionOriginY + gid.y;\n"
   "  if (px >= uniforms.canvasWidth || py >= uniforms.canvasHeight) {\n"
   "    return;\n"
   "  }\n"
   "  const float2 point = float2(float(px) + 0.5f, float(py) + 0.5f);\n"
   "  if (point.x < uniforms.bounds.x - 1.0f || point.y < uniforms.bounds.y - 1.0f ||\n"
   "      point.x > uniforms.bounds.z + 1.0f || point.y > uniforms.bounds.w + 1.0f) {\n"
   "    return;\n"
   "  }\n"
   "  bool inside = winding_at_point(point, vertices, contours, uniforms.contourStart, uniforms.contourCount) != 0;\n"
   "  EdgeDistanceInfo edgeInfo = nearest_path_edge_info(point, vertices, contours, uniforms.contourStart, uniforms.contourCount);\n"
   "  float nearestDistance = edgeInfo.distance;\n"
   "  float signedDistance = inside ? -nearestDistance : nearestDistance;\n"
   "  float coverage = resolve_edge_coverage(signedDistance, edgeInfo.a, edgeInfo.b);\n"
   "  if (coverage <= 1e-6f) {\n"
   "    return;\n"
   "  }\n"
   "  float clipAlpha = uniforms.clipContourCount > 0u\n"
   "    ? analytic_clip_coverage(point, vertices, contours, uniforms.clipContourStart, uniforms.clipContourCount, uniforms.clipBounds)\n"
   "    : sample_clip_alpha(clipTexture, point, uniforms.viewportSize);\n"
   "  float srcA = clamp(uniforms.color.a * coverage * clipAlpha, 0.0f, 1.0f);\n"
   "  if (srcA <= 1e-6f) {\n"
   "    return;\n"
   "  }\n"
   "  float4 src = float4(uniforms.color.rgb * srcA, srcA);\n"
   "  float4 dst = destinationTexture.read(uint2(px, py));\n"
   "  float oneMinusSrcA = 1.0f - srcA;\n"
   "  float4 outColor = float4(src.rgb + dst.rgb * oneMinusSrcA, srcA + dst.a * oneMinusSrcA);\n"
   "  destinationTexture.write(outColor, uint2(px, py));\n"
   "}\n"
   "kernel void composite_texture(\n"
   "  texture2d<float, access::read> sourceTexture [[texture(0)]],\n"
   "  texture2d<float, access::read_write> destinationTexture [[texture(1)]],\n"
   "  constant BlendUniforms& uniforms [[buffer(0)]],\n"
   "  uint2 gid [[thread_position_in_grid]]) {\n"
   "  if (gid.x >= uniforms.width || gid.y >= uniforms.height) {\n"
   "    return;\n"
   "  }\n"
   "  float4 srcPremul = sourceTexture.read(gid);\n"
   "  float4 dstPremul = destinationTexture.read(gid);\n"
   "  float srcA = clamp(srcPremul.a, 0.0f, 1.0f);\n"
   "  float dstA = clamp(dstPremul.a, 0.0f, 1.0f);\n"
   "  float3 src = srcA > 1e-6f ? srcPremul.rgb / srcA : float3(0.0f);\n"
   "  float3 dst = dstA > 1e-6f ? dstPremul.rgb / dstA : float3(0.0f);\n"
   "  if (uniforms.erase != 0u || uniforms.blendMode == 409) {\n"
   "    float removal = clamp(srcA * (uniforms.erase != 0u ? uniforms.eraseStrength : 1.0f), 0.0f, 1.0f);\n"
   "    float keep = 1.0f - removal;\n"
   "    destinationTexture.write(float4(dstPremul.rgb * keep, dstA * keep), gid);\n"
   "    return;\n"
   "  }\n"
   "  if (uniforms.blendMode == 401) {\n"
   "    float4 sumPremul = clamp(dstPremul + srcPremul, 0.0f, 1.0f);\n"
   "    destinationTexture.write(sumPremul, gid);\n"
   "    return;\n"
   "  }\n"
   "  if (uniforms.blendMode == 408) {\n"
   "    destinationTexture.write(srcPremul, gid);\n"
   "    return;\n"
   "  }\n"
   "  float3 blended = canvas_blend_rgb(dst, src, uniforms.blendMode);\n"
   "  float outA = clamp(srcA + dstA - srcA * dstA, 0.0f, 1.0f);\n"
   "  float3 outPremul =\n"
   "    (1.0f - dstA) * srcA * src +\n"
   "    (1.0f - srcA) * dstA * dst +\n"
   "    srcA * dstA * blended;\n"
   "  destinationTexture.write(float4(clamp(outPremul, 0.0f, 1.0f), outA), gid);\n"
   "}\n"
   "float4 copy_read_clamped(texture2d<float, access::read> texture, int2 point) {\n"
   "  int maxX = max(int(texture.get_width()) - 1, 0);\n"
   "  int maxY = max(int(texture.get_height()) - 1, 0);\n"
   "  uint2 clamped = uint2(uint(clamp(point.x, 0, maxX)), uint(clamp(point.y, 0, maxY)));\n"
   "  return texture.read(clamped);\n"
   "}\n"
   "float4 copy_sample_linear(texture2d<float, access::read> texture, float2 uv) {\n"
   "  float2 clampedUv = clamp(uv, float2(0.0f), float2(1.0f));\n"
   "  float2 sourceSize = float2(float(max(texture.get_width(), 1u)), float(max(texture.get_height(), 1u)));\n"
   "  float2 sourcePoint = clampedUv * sourceSize - 0.5f;\n"
   "  float2 base = floor(sourcePoint);\n"
   "  float2 frac = sourcePoint - base;\n"
   "  int2 p00 = int2(base);\n"
   "  int2 p10 = p00 + int2(1, 0);\n"
   "  int2 p01 = p00 + int2(0, 1);\n"
   "  int2 p11 = p00 + int2(1, 1);\n"
   "  float4 c00 = copy_read_clamped(texture, p00);\n"
   "  float4 c10 = copy_read_clamped(texture, p10);\n"
   "  float4 c01 = copy_read_clamped(texture, p01);\n"
   "  float4 c11 = copy_read_clamped(texture, p11);\n"
   "  float4 c0 = mix(c00, c10, frac.x);\n"
   "  float4 c1 = mix(c01, c11, frac.x);\n"
   "  return mix(c0, c1, frac.y);\n"
   "}\n"
   "kernel void copy_texture_to_output(\n"
   "  texture2d<float, access::read> sourceTexture [[texture(0)]],\n"
   "  device float4* destination [[buffer(0)]],\n"
   "  constant CopyUniforms& uniforms [[buffer(1)]],\n"
   "  uint2 gid [[thread_position_in_grid]]) {\n"
   "  if (gid.x >= uniforms.width || gid.y >= uniforms.height) {\n"
   "    return;\n"
   "  }\n"
   "  float logicalWidth = max(float(uniforms.logicalWidth), 1.0f);\n"
   "  float logicalHeight = max(float(uniforms.logicalHeight), 1.0f);\n"
   "  float2 logicalPoint = float2(\n"
   "    uniforms.sourceOriginX + (float(gid.x) + 0.5f) * uniforms.sourceStepX,\n"
   "    uniforms.sourceOriginY + (float(gid.y) + 0.5f) * uniforms.sourceStepY);\n"
   "  if (logicalPoint.x < 0.0f || logicalPoint.y < 0.0f || logicalPoint.x >= logicalWidth || logicalPoint.y >= logicalHeight) {\n"
   "    const uint index = gid.y * uniforms.rowPixels + gid.x;\n"
   "    destination[index] = float4(0.0f);\n"
   "    return;\n"
   "  }\n"
   "  float2 uv = float2(logicalPoint.x / logicalWidth, logicalPoint.y / logicalHeight);\n"
   "  float4 premultiplied = copy_sample_linear(sourceTexture, uv);\n"
   "  float alpha = premultiplied.a;\n"
   "  float3 straight = alpha > 1e-6f ? premultiplied.rgb / alpha : float3(0.0f);\n"
   "  const uint index = gid.y * uniforms.rowPixels + gid.x;\n"
   "  destination[index] = float4(straight.b, straight.g, straight.r, alpha);\n"
   "}\n"
   "float3 filter_straight(float4 premul) {\n"
   "  float a = clamp(premul.a, 0.0f, 1.0f);\n"
   "  return a > 1e-6f ? premul.rgb / a : float3(0.0f);\n"
   "}\n"
   "float filter_luma(float3 rgb) {\n"
   "  return dot(rgb, float3(0.299f, 0.587f, 0.114f));\n"
   "}\n"
   "float4 read_clamped(texture2d<float, access::read> texture, int2 p, uint width, uint height) {\n"
   "  int x = clamp(p.x, 0, max(int(width) - 1, 0));\n"
   "  int y = clamp(p.y, 0, max(int(height) - 1, 0));\n"
   "  return texture.read(uint2(uint(x), uint(y)));\n"
   "}\n"
   "kernel void copy_texture_raw(\n"
   "  texture2d<float, access::read> sourceTexture [[texture(0)]],\n"
   "  texture2d<float, access::write> destinationTexture [[texture(1)]],\n"
   "  constant CopyUniforms& uniforms [[buffer(0)]],\n"
   "  uint2 gid [[thread_position_in_grid]]) {\n"
   "  if (gid.x >= uniforms.width || gid.y >= uniforms.height) {\n"
   "    return;\n"
   "  }\n"
   "  destinationTexture.write(sourceTexture.read(gid), gid);\n"
   "}\n"
   "kernel void apply_filter_texture(\n"
   "  texture2d<float, access::read> sourceTexture [[texture(0)]],\n"
   "  texture2d<float, access::write> destinationTexture [[texture(1)]],\n"
   "  constant FilterUniforms& uniforms [[buffer(0)]],\n"
   "  uint2 gid [[thread_position_in_grid]]) {\n"
   "  if (gid.x >= uniforms.width || gid.y >= uniforms.height) {\n"
   "    return;\n"
   "  }\n"
   "  float4 srcPremul = sourceTexture.read(gid);\n"
   "  float srcA = clamp(srcPremul.a, 0.0f, 1.0f);\n"
   "  float3 srcStraight = filter_straight(srcPremul);\n"
   "  float outA = srcA;\n"
   "  float3 outStraight = srcStraight;\n"
   "  if (uniforms.filterKind == 1) {\n"
   "    float gray = filter_luma(srcStraight);\n"
   "    outStraight = float3(gray);\n"
   "  } else if (uniforms.filterKind == 2) {\n"
   "    outStraight = float3(1.0f) - srcStraight;\n"
   "  } else if (uniforms.filterKind == 3) {\n"
   "    outA = 1.0f;\n"
   "  } else if (uniforms.filterKind == 4) {\n"
   "    float threshold = uniforms.value > 0.0f ? clamp(uniforms.value, 0.0f, 1.0f) : 0.5f;\n"
   "    float gray = filter_luma(srcStraight);\n"
   "    float value = gray >= threshold ? 1.0f : 0.0f;\n"
   "    outStraight = float3(value);\n"
   "  } else if (uniforms.filterKind == 5) {\n"
   "    float levels = max(2.0f, round(uniforms.value));\n"
   "    float step = 1.0f / max(levels - 1.0f, 1.0f);\n"
   "    outStraight = clamp(round(srcStraight / step) * step, 0.0f, 1.0f);\n"
   "  } else if (uniforms.filterKind == 6) {\n"
   "    int radius = int(round(uniforms.value > 0.0f ? uniforms.value : 1.0f));\n"
   "    radius = clamp(radius, 1, 16);\n"
   "    float3 sumStraight = float3(0.0f);\n"
   "    float sumA = 0.0f;\n"
   "    int count = 0;\n"
   "    for (int oy = -16; oy <= 16; ++oy) {\n"
   "      if (abs(oy) > radius) {\n"
   "        continue;\n"
   "      }\n"
   "      for (int ox = -16; ox <= 16; ++ox) {\n"
   "        if (abs(ox) > radius) {\n"
   "          continue;\n"
   "        }\n"
   "        float4 samplePremul = read_clamped(sourceTexture, int2(int(gid.x) + ox, int(gid.y) + oy), uniforms.width, uniforms.height);\n"
   "        float sampleA = clamp(samplePremul.a, 0.0f, 1.0f);\n"
   "        sumStraight += filter_straight(samplePremul);\n"
   "        sumA += sampleA;\n"
   "        count += 1;\n"
   "      }\n"
   "    }\n"
   "    if (count > 0) {\n"
   "      outStraight = sumStraight / float(count);\n"
   "      outA = sumA / float(count);\n"
   "    }\n"
   "  } else if (uniforms.filterKind == 7 || uniforms.filterKind == 8) {\n"
   "    bool erode = uniforms.filterKind == 7;\n"
   "    float4 chosenPremul = srcPremul;\n"
   "    float chosenLuma = filter_luma(srcStraight);\n"
   "    for (int oy = -1; oy <= 1; ++oy) {\n"
   "      for (int ox = -1; ox <= 1; ++ox) {\n"
   "        float4 samplePremul = read_clamped(sourceTexture, int2(int(gid.x) + ox, int(gid.y) + oy), uniforms.width, uniforms.height);\n"
   "        float sampleLuma = filter_luma(filter_straight(samplePremul));\n"
   "        bool replace = (erode && sampleLuma < chosenLuma) || (!erode && sampleLuma > chosenLuma);\n"
   "        if (replace) {\n"
   "          chosenPremul = samplePremul;\n"
   "          chosenLuma = sampleLuma;\n"
   "        }\n"
   "      }\n"
   "    }\n"
   "    outA = clamp(chosenPremul.a, 0.0f, 1.0f);\n"
   "    outStraight = filter_straight(chosenPremul);\n"
   "  }\n"
   "  outA = clamp(outA, 0.0f, 1.0f);\n"
   "  outStraight = clamp(outStraight, 0.0f, 1.0f);\n"
   "  destinationTexture.write(float4(outStraight * outA, outA), gid);\n"
   "}\n"
   "kernel void apply_mask_texture(\n"
   "  texture2d<float, access::read> sourceTexture [[texture(0)]],\n"
   "  texture2d<float, access::read> maskTexture [[texture(1)]],\n"
   "  texture2d<float, access::write> destinationTexture [[texture(2)]],\n"
   "  constant CopyUniforms& uniforms [[buffer(0)]],\n"
   "  uint2 gid [[thread_position_in_grid]]) {\n"
   "  if (gid.x >= uniforms.width || gid.y >= uniforms.height) {\n"
   "    return;\n"
   "  }\n"
   "  float4 srcPremul = sourceTexture.read(gid);\n"
   "  float maskAlpha = clamp(maskTexture.read(gid).a, 0.0f, 1.0f);\n"
   "  destinationTexture.write(float4(srcPremul.rgb * maskAlpha, srcPremul.a * maskAlpha), gid);\n"
   "}\n";
  return source;
}

}  // namespace metal
}  // namespace bitmap
}  // namespace momentum
